"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(aqmnx)ehgbv0v0tu950=u@ou6i+!)_yoph6q)i)&ys3k@62%='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',              # <--- EN ÜSTE BUNU EKLE (Çok Önemli!)
    'django.contrib.admin', # <--- Bu bunun altında kalmalı
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filmler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
import os # Eğer en tepede import os yoksa buraya ekle

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- JAZZMIN ADMIN PANELİ AYARLARI ---

JAZZMIN_SETTINGS = {
    "site_title": "FilmKutusu Admin",
    "site_header": "FilmKutusu",
    "site_brand": "FilmKutusu",
    "site_logo": "logo.png", # Senin statik klasöründeki logo
    "login_logo": "logo.png",
    "welcome_sign": "FilmKutusu Yönetim Paneline Hoşgeldiniz",
    "copyright": "FilmKutusu Ltd",
    "search_model": ["filmler.Film"], # Üstteki arama çubuğu direkt filmleri arar
    
    # Menü Ayarları
    "topmenu_links": [
        {"name": "Siteye Git", "url": "home", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["filmler", "auth"], # Menü sıralaması
    
    # İkonlar (Bootstrap Icons)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "filmler.Film": "fas fa-film",       # Film ikonu
        "filmler.Yorum": "fas fa-comments",  # Yorum ikonu
        "filmler.Iletisim": "fas fa-envelope", # Mesaj ikonu
    },
}

# --- RENK VE TEMA AYARLARI (DARK MODE) ---
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",         # Karanlık Tema (Cyborg veya Darkly)
    "navbar": "navbar-dark",   # Üst menü siyah
    "sidebar": "sidebar-dark-danger", # Yan menü siyah, vurgular KIRMIZI
    "brand_colour": "navbar-danger",  # Logo arkası kırmızı
    "accent": "accent-danger",        # Butonlar ve linkler kırmızı
    "button_classes": {
        "primary": "btn-danger",      # Ana butonlar kırmızı
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}