# Generated by Django 5.2.8 on 2025-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('konu', models.TextField()),
                ('resim', models.CharField(default='https://via.placeholder.com/300', max_length=300)),
                ('puan', models.IntegerField(default=0)),
            ],
        ),
    ]
