# Generated by Django 5.2.8 on 2025-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tur',
            field=models.CharField(choices=[('Aksiyon', 'Aksiyon'), ('Komedi', 'Komedi'), ('Bilim Kurgu', 'Bilim Kurgu'), ('Dram', 'Dram'), ('Korku', 'Korku')], default='Aksiyon', max_length=50),
        ),
    ]
