# Generated by Django 5.2.8 on 2025-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0002_film_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='oyuncular',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='film',
            name='yonetmen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
