# Generated by Django 5.2.8 on 2025-11-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0003_film_oyuncular_film_yonetmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='İsim')),
                ('icerik', models.TextField(verbose_name='Yorumunuz')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='filmler.film')),
            ],
        ),
    ]
