# Generated by Django 5.2.8 on 2025-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0004_yorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
