# Generated by Django 5.2.8 on 2025-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0006_yorum_kullanici_alter_yorum_isim_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='izleme_listesi',
            field=models.ManyToManyField(blank=True, related_name='listeye_alanlar', to='filmler.film'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/149/149071.png', max_length=300),
        ),
    ]
