# Generated by Django 5.2.8 on 2025-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0007_profil_izleme_listesi_alter_profil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='puan',
            field=models.IntegerField(default=10, verbose_name='Puanın'),
        ),
    ]
