# Generated by Django 5.2.8 on 2025-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0008_yorum_puan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='oyun_puani',
            field=models.IntegerField(default=0),
        ),
    ]
